### ISSUE TITLE
Problem using (for i in range) loop to define the Sections and Elements

### ISSUE THREAD

**Issue by gamecult2** [zhuminjie/OpenSeesPyDoc#235]
Dear Dr,
First of all I want to thank you for these wonderful tools which help a lot, Thank you so much.
I am currently using OpenSeesPy for analysis but I had some problem that I cannot fix.
Please I would like to know if it is possible to use loops to define Sections and Elements to reduce the code ?
I tried to use them in my code and always have problem `opensees.OpenSeesError: See stderr output` and I didn't find how to fix them. 
The simplified version of my scripts is shown below (note that the script is used to showcase what I intend to do).

```python
from openseespy.opensees import *
import numpy as np
#                             1   2   3   4   5   6   7   8   9   10  11  12  13  14  15  16  17  18  19  20  21  22  23  24
element_length = np.array([0, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,  4])

CoverSec = 0.05
for i in range(1, len(element_length)):
    Circumference_Section[i] = DSec[i] * math.pi
    numBarsSec[i] = Number_Reinforcement[i] = int(round(Circumference_Section[i] / Rebar_spacing_VO[i]))
    barAreaSec = math.pi / 4 * Rebar_diameter_VO ** 2
    ColSecTag[i] = Column_Section_Tag[i] = i
    ro[i] = DSec[i] / 2
    ri[i] = ro[i] - TSec[i]
    nfCoreR = 8                             # number of radial divisions in the core (number of "rings")
    nfCoreT[i] = numBarsSec[i]              # number of theta divisions in the core (number of "wedges")
    nfCoverR = 4                            # number of radial divisions in the cover
    nfCoverT[i] = numBarsSec[i]             # number of theta divisions in the cover
    rc[i] = ro[i] - CoverSec                # Core radius
    rc2[i] = ri[i] + CoverSec
    theta[i] = 360.0 / numBarsSec[i]        # Determine angle increment between bars

for i in range(1, len(element_length)):
    section('Fiber', i)        # Error line 172
    patch('circ', IDconcCoverC40, nfCoverT[i], nfCoverR, 0, 0, rc[i], ro[i], 0, 360)
    layer('circ', IDreinf, numBarsSec[i], barAreaSec[i], 0., 0., rc[i], theta[i], 360)
    patch('circ', IDconcCoreC40, nfCoreT[i], nfCoreR, 0., 0., rc2[i], rc[i], 0., 360)
    layer('circ', IDreinf, numBarsSec[i], barAreaSec[i], 0., 0., rc2[i], theta[i], 360)
    patch('circ', IDconcCoverC40, nfCoverT[i], nfCoverR, 0., 0., ri[i], rc2[i], 0., 360)
```
```
Traceback (most recent call last):
  File "C:/Users/djerr/PycharmProjects/OpenSeesPy/chimney.py", line 172, in <module>
    section('Fiber', ColSecTag[i])
opensees.OpenSeesError: See stderr output
```
Same thing to define the Elements :
```python
ColTransfTag = 1
geomTransf('PDelta',  ColTransfTag)  		             # associate a tag to transformation

for i in range(0, len(element_length)):
    element('nonlinearBeamColumn', i, *[i, i+1], 5, ColSecTag[i], 1)
```
```
WARNING invalid int inputs
Traceback (most recent call last):
  File "C:/Users/djerr/PycharmProjects/OpenSeesPy/chimney.py", line 199, in <module>
    element('nonlinearBeamColumn', i, *[i, i+1], 5, ColSecTag[i], 1)
opensees.OpenSeesError: See stderr output
```

Example of defined Fiber Section :

![Figure_1](https://user-images.githubusercontent.com/74660921/120617717-f6cc9400-c48c-11eb-804f-77936cdd70b5.png)

The full code is here (work in progress) https://github.com/gamecult2/OpenSees/blob/main/chimney.py
Thank you very much for your time!
Best,

**Comment by gamecult2** [comment]
Looks like the problem is in using Numpy Array
I had to convert the numpy.array to a normal list to correct the problem, and I only converted for the following 3 variables below 
```python
nfCoverT = nfCoverT.tolist()                 # Converting one-dimensional NumPy Array to List
nfCoreT = nfCoreT.tolist()
numBarsSec = numBarsSec.tolist()
for i in range(1, len(element_length)):
    section('Fiber', i)        # Error line 172
    patch('circ', IDconcCoverC40, nfCoverT[i], nfCoverR, 0, 0, rc[i], ro[i], 0, 360)
    layer('circ', IDreinf, numBarsSec[i], barAreaSec[i], 0., 0., rc[i], theta[i], 360)
    patch('circ', IDconcCoreC40, nfCoreT[i], nfCoreR, 0., 0., rc2[i], rc[i], 0., 360)
    layer('circ', IDreinf, numBarsSec[i], barAreaSec[i], 0., 0., rc2[i], theta[i], 360)
    patch('circ', IDconcCoverC40, nfCoverT[i], nfCoverR, 0., 0., ri[i], rc2[i], 0., 360)
```

**Comment by zhuminjie** [comment]
The data type for items in numpy.array is numpy.int64 instead of int. Try 
```python
A = np.array([1,2,3])
type(A[0])
```
