### ISSUE TITLE
Using Opensees in 3D Analysis

### ISSUE THREAD

**Issue by xmiki9** [zhuminjie/OpenSeesPyDoc#251]
Good evening guys, I have a problem, I am working on a code to see the 3d analysis of reinforced concrete elements and I am using opensees. The problem is when running the code, I get the following message:

```
PS C:\Users\miki\Desktop\test\test1> & "C:/Program Files/Python38/python.exe" "C:\Users\miki\Desktop\test\test1/01. Qt Designer/main.py"
CrdTransf *getCrdTransf(int tag) - none found with tag: 0
no CrdTransf is found
Traceback (most recent call last):
  File "C:\Users\miki\Desktop\test\test1/01. Qt Designer/main.py", line 20, in <lambda>
    self.ui.btn_analizar.clicked.connect(lambda: UIFunctions.plotear_modelo_modos(self))
  File "C:\Users\miki\Desktop\test\test1/01. Qt Designer\functions.py", line 125, in plotear_modelo_modos
    element('elasticBeamColumn', int(Ele[0]), int(Ele[1]), int(Ele[2]), Av, E, G, Jxxv, Iyv, Izv, int(Ele[3]),'-mass', densidad*Av)
opensees.OpenSeesError: See stderr output
```

Please, if anyone has had a similar problem and I can help, I would greatly appreciate it. Thank you very much in advance.

**Comment by mhscott** [comment]
Sorry, this is not an OpenSeesPy issue. Please post on the OpenSees message board:
https://opensees.berkeley.edu/community
