### ISSUE TITLE
pip install on Mac with M1 chip

### ISSUE THREAD

**Issue by pollinico** [zhuminjie/OpenSeesPyDoc#310]
Hi, I pip installed openseespy on my minimac with M1 chip.
I am running a miniconda for osx-arm64.
Is openseespy supported for these machines? Or perhaps it works only for mac with Intel chip or Rosetta?

```bash
>>> import openseespy.opensees
Traceback (most recent call last):
  File "/Users/nicolo/miniconda3/envs/opensees-env/lib/python3.11/site-packages/openseespy/opensees/__init__.py", line 27, in <module>
    from openseespymac.opensees import *
ImportError: dlopen(/Users/nicolo/miniconda3/envs/opensees-env/lib/python3.11/site-packages/openseespymac/opensees.so, 0x0002): tried: '/Users/nicolo/miniconda3/envs/opensees-env/lib/python3.11/site-packages/openseespymac/opensees.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e' or 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/nicolo/miniconda3/envs/opensees-env/lib/python3.11/site-packages/openseespymac/opensees.so' (no such file), '/Users/nicolo/miniconda3/envs/opensees-env/lib/python3.11/site-packages/openseespymac/opensees.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e' or 'arm64'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/nicolo/miniconda3/envs/opensees-env/lib/python3.11/site-packages/openseespy/opensees/__init__.py", line 30, in <module>
    raise RuntimeError('Failed to import openseespy on Mac.')
RuntimeError: Failed to import openseespy on Mac.
```   

```bash
>>> import openseespymac.opensees
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: dlopen(/Users/nicolo/miniconda3/envs/opensees-env/lib/python3.11/site-packages/openseespymac/opensees.so, 0x0002): tried: '/Users/nicolo/miniconda3/envs/opensees-env/lib/python3.11/site-packages/openseespymac/opensees.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e' or 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/nicolo/miniconda3/envs/opensees-env/lib/python3.11/site-packages/openseespymac/opensees.so' (no such file), '/Users/nicolo/miniconda3/envs/opensees-env/lib/python3.11/site-packages/openseespymac/opensees.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e' or 'arm64'))
```

**Comment by zhuminjie** [comment]
No, does work for m1,m2,m3.

**Comment by pollinico** [comment]
thank you for your reply!
